<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\VolumeProfileManager.Core\VolumeProfileManager.Core.csproj" />
    <ProjectReference Include="..\VolumeProfileManager.Domain\VolumeProfileManager.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.2.0" />
    <PackageReference Include="Serilog" Version="3.1.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
